// <auto-generated />
using System;
using AficFrio.Api.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AficFrio.Api.Migrations
{
    [DbContext(typeof(DBRestaurante))]
    [Migration("20251028002753_Ini")]
    partial class Ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AficFrio.Shared.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QRCodeMobile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Empresa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Dev's Burguer",
                            QRCodeMobile = "Pendente"
                        });
                });

            modelBuilder.Entity("AficFrio.Shared.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CadastradoEm = new DateTime(2025, 10, 21, 21, 27, 52, 657, DateTimeKind.Local).AddTicks(8311),
                            Email = "admin@admin.com",
                            EmpresaId = 1,
                            Role = 1,
                            Senha = "gfse3McKBuFWBrNpAwRVDg==",
                            Username = "User"
                        },
                        new
                        {
                            Id = 2,
                            CadastradoEm = new DateTime(2025, 10, 21, 21, 27, 52, 657, DateTimeKind.Local).AddTicks(8459),
                            Email = "admin@admin.com",
                            EmpresaId = 1,
                            Role = 2,
                            Senha = "gfse3McKBuFWBrNpAwRVDg==",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CadastradoEm = new DateTime(2025, 10, 21, 21, 27, 52, 657, DateTimeKind.Local).AddTicks(8461),
                            Email = "admin@admin.com",
                            EmpresaId = 1,
                            Role = 3,
                            Senha = "gfse3McKBuFWBrNpAwRVDg==",
                            Username = "RafaDev"
                        });
                });

            modelBuilder.Entity("AficFrio.Shared.Models.Usuario", b =>
                {
                    b.HasOne("AficFrio.Shared.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
